### ISSUE TITLE
What transitions are possible currently? Is structure suitable?

### ISSUE THREAD

**Issue by lewismcgeary** [derwinmcgeary/VroomVroom#5]
Currently we can hide/display appropriate sections based on tags. Is it possible to have graceful transitions using this method? If we can go to previous/next section by an elastic pull-to-display mechanism at the top and bottom of the screen, what does this look like?

Alternative thoughts on content:
-break sections back into individual html pages
-use one html page for the content but use two(or more?) webviews in a recycler view. One webview could have loaded in html content and display content id (100-105), next webview could display (105-110), we could presumably then scroll up-down between them by moving the webviews rather than simply the javascript, hide-one, display-other method

**Comment by derwinmcgeary** [comment]
We have changed the structure, making this issue no longer relevant
